// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-p4ltqu4KaTbM_tHU3bj6mUNF0fKClHw',
    appId: '1:479629486891:web:6ad253567c8056cc2bf36e',
    messagingSenderId: '479629486891',
    projectId: 'todo-d7a68',
    authDomain: 'todo-d7a68.firebaseapp.com',
    storageBucket: 'todo-d7a68.firebasestorage.app',
    measurementId: 'G-X2YLVXCEW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD5HQZCtzgnLobkIj729E9Iji7Et1ya9E',
    appId: '1:479629486891:android:b4d2c0f510be7a0b2bf36e',
    messagingSenderId: '479629486891',
    projectId: 'todo-d7a68',
    storageBucket: 'todo-d7a68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD4Vm7c7saOUxNWUtXTHw7UKD7S5_SvhQ',
    appId: '1:479629486891:ios:6e8bc5b30f6823842bf36e',
    messagingSenderId: '479629486891',
    projectId: 'todo-d7a68',
    storageBucket: 'todo-d7a68.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD4Vm7c7saOUxNWUtXTHw7UKD7S5_SvhQ',
    appId: '1:479629486891:ios:6e8bc5b30f6823842bf36e',
    messagingSenderId: '479629486891',
    projectId: 'todo-d7a68',
    storageBucket: 'todo-d7a68.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-p4ltqu4KaTbM_tHU3bj6mUNF0fKClHw',
    appId: '1:479629486891:web:f3d4194ddf48c3fb2bf36e',
    messagingSenderId: '479629486891',
    projectId: 'todo-d7a68',
    authDomain: 'todo-d7a68.firebaseapp.com',
    storageBucket: 'todo-d7a68.firebasestorage.app',
    measurementId: 'G-6L0TG6X1RK',
  );
}
